name: Deploy to Databricks

on:
  pull_request:
    branches: [main]
    paths:
      - 'databricks-bundles/**'
  
  push:
    branches: [main]
    paths:
      - 'databricks-bundles/**'

jobs:
  deploy-dev:
    name: Deploy to DEV
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          export PATH=$PATH:$HOME/.databricks/bin
      
      - name: Deploy to Dev
        working-directory: ./databricks-bundles
        run: |
          export PATH=$PATH:$HOME/.databricks/bin
          
          # Create Databricks config
          cat > ~/.databrickscfg << EOF
          [DEFAULT]
          host = https://adb-7405617333572408.8.azuredatabricks.net
          azure_tenant_id = ${{ secrets.DATABRICKS_TENANT_ID }}
          azure_client_id = ${{ secrets.DATABRICKS_CLIENT_ID }}
          azure_client_secret = ${{ secrets.DATABRICKS_CLIENT_SECRET }}
          auth_type = azure-client-secret
          EOF
          
          databricks bundle deploy --target dev --force-lock
          
  deploy-prod:
    name: Deploy to PROD
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          export PATH=$PATH:$HOME/.databricks/bin
      
      - name: Deploy to Prod
        working-directory: ./databricks-bundles
        run: |
          export PATH=$PATH:$HOME/.databricks/bin
          
          # Create Databricks config
          cat > ~/.databrickscfg << EOF
          [DEFAULT]
          host = https://adb-7405616246068137.17.azuredatabricks.net
          azure_tenant_id = ${{ secrets.DATABRICKS_TENANT_ID }}
          azure_client_id = ${{ secrets.DATABRICKS_CLIENT_ID }}
          azure_client_secret = ${{ secrets.DATABRICKS_CLIENT_SECRET }}
          auth_type = azure-client-secret
          EOF
          
          databricks bundle deploy --target prod --force-lock